version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
        
  keycloak:
      image: jboss/keycloak
      container_name: local_keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_PORT: 5432
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: keycloak
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8080:8080
      depends_on:
        - postgres